# Generated by Django 6.0.2 on 2026-02-17 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StraceAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("file", "Uploaded File"),
                            ("text", "Pasted Text"),
                            ("sample", "Sample File"),
                            ("live", "Live Trace"),
                            ("synthetic", "Synthetic Data"),
                        ],
                        max_length=50,
                    ),
                ),
                ("filename", models.CharField(blank=True, default="", max_length=200)),
                (
                    "uploaded_file",
                    models.FileField(
                        blank=True, null=True, upload_to="strace_uploads/"
                    ),
                ),
                ("total_syscalls", models.IntegerField(default=0)),
                ("analysis_json", models.TextField(default="{}")),
                ("recommendations_json", models.TextField(default="[]")),
                ("syscall_summary_json", models.TextField(default="{}")),
                ("category_summary_json", models.TextField(default="{}")),
                ("parse_stats_json", models.TextField(default="{}")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Strace Analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExportHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("script", "Shell Script"),
                            ("json", "JSON Report"),
                            ("markdown", "Markdown Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filename", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.straceanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Export Histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
